import mongoose, { Schema, Document, Types } from 'mongoose';

export enum POStatus {
  DRAFT = 'DRAFT',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  SENT = 'SENT',
  PARTIALLY_RECEIVED = 'PARTIALLY_RECEIVED',
  FULFILLED = 'FULFILLED',
  CANCELLED = 'CANCELLED',
}

export interface IPOItem {
  product: Types.ObjectId;
  quantityOrdered: number;
  quantityReceived: number;
  expectedPrice?: number;
}

export interface IPurchaseOrder extends Document {
  poNumber: string;
  tenantId: Types.ObjectId;
  branchId: Types.ObjectId;
  supplierId: Types.ObjectId;
  items: IPOItem[];
  status: POStatus;
  autoGenerated: boolean;
  totalEstimatedValue: number;
  expectedDeliveryDate?: Date;
  notes?: string;
  createdAt: Date;
  updatedAt: Date;
}

const poItemSchema = new Schema<IPOItem>(
  {
    product: { type: Schema.Types.ObjectId, ref: 'Product', required: true },
    quantityOrdered: { type: Number, required: true, min: 1 },
    quantityReceived: { type: Number, default: 0, min: 0 },
    expectedPrice: { type: Number },
  },
  { _id: false }
);

const purchaseOrderSchema = new Schema<IPurchaseOrder>(
  {
    poNumber: { type: String, required: true, unique: true, uppercase: true },
    tenantId: {
      type: Schema.Types.ObjectId,
      ref: 'Tenant',
      required: true,
    },
    branchId: {
      type: Schema.Types.ObjectId,
      ref: 'Branch',
      required: true,
    },
    supplierId: { type: Schema.Types.ObjectId, ref: 'Supplier', required: true, index: true },
    items: { type: [poItemSchema], required: true },
    status: { type: String, enum: Object.values(POStatus), default: POStatus.DRAFT, index: true },
    autoGenerated: { type: Boolean, default: false },
    totalEstimatedValue: { type: Number, default: 0 },
    expectedDeliveryDate: { type: Date },
    notes: { type: String },
  },
  { timestamps: true }
);

// Pre-validate hook: auto-generate unique PO number if not set
purchaseOrderSchema.pre('validate', function (next) {
  if (!this.poNumber) {
    const timestamp = Date.now();
    const randomStr = Math.random().toString(36).substring(2, 6).toUpperCase();
    this.poNumber = `PO-${timestamp}-${randomStr}`;
  }
  next();
});

export default mongoose.model<IPurchaseOrder>('PurchaseOrder', purchaseOrderSchema);
